[package]
name = "hello_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.7"
serde = "1.0.210"
serde_json = "1.0"
tokio = "1.40.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[[bin]]
name = "greet" # The name of your Netlify function
path = "greet.rs" 
