[build]
  command = "rustup install stable && rustup default stable && cd frontend && cargo build --release && cd .. && cd functions && cargo build --release"
  publish = "frontend/target/release"
  functions = "functions/target/release"